/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2018-07-26 08:43:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mrp.web.vo.PageInfo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import mrp.web.vo.Board;
import mrp.web.vo.BoardBo;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mrp.web.vo.Board");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("mrp.web.vo.BoardBo");
    _jspx_imports_classes.add("mrp.web.vo.PageInfo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	ArrayList<BoardBo> boardBoList = (ArrayList<BoardBo>) request.getAttribute("boardBoList");
	Board board = (Board) request.getAttribute("board");
	/* String pageNum = (String)session.getAttribute("pageNum"); */
	int b_division = (int) request.getAttribute("b_division");

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>DAEGU</title>\r\n");
      out.write("<style>\r\n");
      out.write(".ggaggoong {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ggaggoong2 {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".smalltext {\r\n");
      out.write("\tfont-size: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".smalltext:active { .ggaggoong { display:block;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board_content1 {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#board_title {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\tborder-bottom: 1px solid #bcbcbc;\r\n");
      out.write("\tmargin-bottom: 1%;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contentArea {\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: solid 1px #bcbcbc;\r\n");
      out.write("\tpadding-bottom: 2%;\r\n");
      out.write("\tbackground-color: #FAFAFA;\r\n");
      out.write("\tpadding: 1.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#basicContent {\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\tborder-bottom: 3px double orange;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#detailContent {\r\n");
      out.write("\tmargin-top: 2.5%;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#commandArea {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tmargin-right: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".td_Readcount {\r\n");
      out.write("\tborder-bottom: 1px solid #bcbcbc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#reftext {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\tmargin-top: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dat_content {\r\n");
      out.write("\tborder-bottom: 1px solid #bcbcbc;\r\n");
      out.write("\twidth: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".smalltext {\r\n");
      out.write("\tcolor: #817E7E;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#datgul {\r\n");
      out.write("\tbackground: #F2F1F1;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function textview(code) {\r\n");
      out.write("\tdocument.getElementById(\"dattext\"+code).style.display = \"inline-block\";\r\n");
      out.write("\tdocument.getElementById(\"data\"+code).style.display = \"inline-block\";\r\n");
      out.write("}\r\n");
      out.write("function sujung(code){\r\n");
      out.write("\tdocument.getElementById(\"content\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"sujung\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"delete\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"dat\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"inputtext\"+code).style.display=\"inline\";\r\n");
      out.write("\tdocument.getElementById(\"ok\"+code).style.display=\"inline\";\r\n");
      out.write("\tdocument.getElementById(\"no\"+code).style.display=\"inline\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function ok(code) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar text=document.getElementById(\"inputtext\"+code).value;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function no(code) {\r\n");
      out.write("\tdocument.getElementById(\"ok\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"no\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"inputtext\"+code).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById(\"content\"+code).style.display=\"inline\";\r\n");
      out.write("\tdocument.getElementById(\"dat\"+code).style.display=\"inline\";\r\n");
      out.write("\tdocument.getElementById(\"sujung\"+code).style.display=\"inline\";\r\n");
      out.write("\tdocument.getElementById(\"delete\"+code).style.display=\"inline\";\r\n");
      out.write("}\r\n");
      out.write("function boardDelete(b_code, b_division) {\r\n");
      out.write("\tvar check=confirm(\"삭제 하시겠습니까?\");\r\n");
      out.write("\tif(check==true){\r\n");
      out.write("\t\tlocation.href=\"boardDelete.bo?b_code=\"+b_code+\"&b_division=\"+b_division;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function textDatDelete(d_code,b_code,b_division) {\r\n");
      out.write("\tvar check=confirm(\"삭제 하시겠습니까?\");\r\n");
      out.write("\tif(check==true){\r\n");
      out.write("\t\tlocation.href=\"datDelete.bo?d_code=\"+d_code+\"&b_code=\"+b_code+\"&b_division=\"+b_division;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"contentArea\">\r\n");
      out.write("\t\t<h1>자신의 작성글은 본인의 얼굴입니다^^ 예쁘게 작성해주세요^^</h1>\r\n");
      out.write("\t\t<div class=\"basicContent\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><label for=\"board_title\"></label></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_right\" id=\"board_title\">");
      out.print(board.getB_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><label for=\"board_writer\"></label></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_right\" id=\"board_writer\">");
      out.print(board.getB_author());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<!-- \t\t\t<br> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<section id=\"detailContent\">\r\n");
      out.write("\t\t\t<pre class=\"board_content1\">");
      out.print(board.getB_content());
      out.write("</pre>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"td_Readcount\"><label for=\"board_Readcount\">조회수</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"td_Readcount\" id=\"board_Readcount\">");
      out.print(board.getReadcount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table id=\"datgul\">\r\n");
      out.write("\t\t\t");

				int i = 0;
				int u_division = (Integer) session.getAttribute("u_division");
				String u_name = (String) session.getAttribute("u_name");
				if (boardBoList != null) {
					for (i = 0; i < boardBoList.size(); i++) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr class=\"dat_title\">\r\n");
      out.write("\t\t\t\t<td class=\"dat_content\">\r\n");
      out.write("\t\t\t\t\t");

						for (int j = 0; j < boardBoList.get(i).getRe_step(); j++) {
					
      out.write(" &nbsp;&nbsp; ");

 	}
 
      out.write(' ');
      out.print(boardBoList.get(i).getD_author());
      out.write(" :\r\n");
      out.write("\t\t\t\t\t<p id=\"content");
      out.print(boardBoList.get(i).getD_code());
      out.write('"');
      out.write('>');
      out.print(boardBoList.get(i).getD_content());
      out.write("\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<form\r\n");
      out.write("\t\t\t\t\t\taction=\"datRemake.bo?b_division=");
      out.print(b_division);
      out.write("&d_code=");
      out.print(boardBoList.get(i).getD_code());
      out.write("&b_code=");
      out.print(boardBoList.get(i).getD_boardcode());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tmethod=\"post\" id=\"remake");
      out.print(boardBoList.get(i).getD_code());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"inputtext");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"inputtext");
      out.print(boardBoList.get(i).getD_code());
      out.write("\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ggaggoong\" value=\"");
      out.print(boardBoList.get(i).getD_content());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" id=\"ok");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ggaggoong\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"document.getElementById('remake");
      out.print(boardBoList.get(i).getD_code());
      out.write("').submit();\">확인</a>\r\n");
      out.write("\t\t\t\t\t</form> <a href=\"#\" id=\"no");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"ggaggoong\" onclick=\"no(");
      out.print(boardBoList.get(i).getD_code());
      out.write(")\">취소</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" id=\"dat");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"smalltext\"\r\n");
      out.write("\t\t\t\t\tonclick=\"textview(");
      out.print(boardBoList.get(i).getD_code());
      out.write(")\">댓글</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t");

						if (boardBoList.get(i).getD_author().equals(u_name) || u_division == 0) {
					
      out.write(" <a href=\"#\" id=\"sujung");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"smalltext\"\r\n");
      out.write("\t\t\t\t\tonclick=\"sujung(");
      out.print(boardBoList.get(i).getD_code());
      out.write(")\">수정</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" id=\"delete");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"smalltext\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='datDelete.bo?b_division=");
      out.print(b_division);
      out.write("&d_code=");
      out.print(boardBoList.get(i).getD_code());
      out.write("&b_code=");
      out.print(boardBoList.get(i).getD_boardcode());
      out.write("'\">삭제</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<form method=\"post\"\r\n");
      out.write("\t\t\t\t\t\taction=\"boardContentDat.bo?b_division=");
      out.print(b_division);
      out.write("&d_code=");
      out.print(boardBoList.get(i).getD_code());
      out.write("&b_code=");
      out.print(boardBoList.get(i).getD_boardcode());
      out.write("&name=");
      out.print(u_name);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"dattext");
      out.print(boardBoList.get(i).getD_code());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"dattext");
      out.print(boardBoList.get(i).getD_code());
      out.write("\" class=\"ggaggoong\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 텍스트 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"ggaggoong\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"data");
      out.print(boardBoList.get(i).getD_code());
      out.write("\" value=\"작성\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}

				}
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<form method=\"post\"\r\n");
      out.write("\t\t\taction=\"boardContentDatRef.bo?ref=");
      out.print(i);
      out.write("&name=");
      out.print(u_name);
      out.write("&b_code=");
      out.print(board.getB_code());
      out.write("&b_division=");
      out.print(b_division);
      out.write(" \">\r\n");
      out.write("\t\t\t<input id=\"reftext\" type=\"text\" name=\"reftext\"><input\r\n");
      out.write("\t\t\t\ttype=\"submit\" value=\"댓글입력\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"commandArea\">\r\n");
      out.write("\t\t");

			if (board.getB_author().equals(u_name) || u_division == 0) {
		
      out.write("\r\n");
      out.write("\t\t<a\r\n");
      out.write("\t\t\thref=\"boardRemakeForm.bo?b_code=");
      out.print(board.getB_code());
      out.write("&b_content=");
      out.print(board.getB_content());
      out.write("&b_name=");
      out.print(board.getB_name());
      out.write("&b_mcode=");
      out.print(board.getB_mcode());
      out.write("&b_division=");
      out.print(board.getB_division());
      out.write("\"\r\n");
      out.write("\t\t\tid=\"contentsujung\" class=\"smalltext\">수정</a>&nbsp; <a\r\n");
      out.write("\t\t\tid=\"contentdelete\" class=\"smalltext\"\r\n");
      out.write("\t\t\tonclick=\"boardDelete(");
      out.print(board.getB_code());
      out.write(',');
      out.print(b_division);
      out.write(")\">삭제</a>&nbsp;\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t");

			if (b_division == 3 || b_division == 6) {
		
      out.write("\r\n");
      out.write("\t\t<a href=\"eventBoardList.bo?b_division=");
      out.print(b_division);
      out.write("\">목록보기</a>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<a href=\"boardList.bo?b_division=");
      out.print(b_division);
      out.write("\">목록보기</a>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
