/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2018-07-26 06:08:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$(document)\r\n");
      out.write("\t\t\t\t\t\t\t\t.keydown(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(event) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (event.ctrlKey == true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t&& (event.which == '61'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|| event.which == '107'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|| event.which == '173'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|| event.which == '109'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|| event.which == '187' || event.which == '189')) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(window).bind('mousewheel DOMMouseScroll',\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction(event) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (event.ctrlKey == true) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".con {\r\n");
      out.write("\twidth: 1500px;\r\n");
      out.write("\theight: 800px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tmargin-left: -750px;\r\n");
      out.write("\tmargin-top: -400px;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".con2 {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 55%;\r\n");
      out.write("\ttop: 35%;\r\n");
      out.write("\tmargin-left: -300px;\r\n");
      out.write("\tmargin-top: -100px;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 55%;\r\n");
      out.write("\ttop: 55%;\r\n");
      out.write("\tmargin-left: -300px;\r\n");
      out.write("\tmargin-top: -100px;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#u_pw {\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#u_id {\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input::placeholder {\r\n");
      out.write("\tcolor: #E9E6E1;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: #DED8CD;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submits {\r\n");
      out.write("\tborder: 1px solid #180f4f;\r\n");
      out.write("\tbackground-image: url(images/login.png);\r\n");
      out.write("\tbackground-size: 500px 40px;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".join {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 55%;\r\n");
      out.write("\tbottom: 28%;\r\n");
      out.write("\tmargin-left: -300px;\r\n");
      out.write("\tmargin-top: -100px;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".join>a {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find>a {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 55%;\r\n");
      out.write("\tbottom: 28%;\r\n");
      out.write("\tmargin-left: -50px;\r\n");
      out.write("\tmargin-top: -100px;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bloc {\r\n");
      out.write("\twidth : 80%;\r\n");
      out.write("\tmargin : 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>너의 영화는</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\thistory.pushState(null, null, location.href);\r\n");
      out.write("\t\twindow.onpopstate = function() {\r\n");
      out.write("\t\t\thistory.go(1);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"bloc\">\r\n");
      out.write("\t\t<form action=\"loginProcess.log\" method=\"POST\">\r\n");
      out.write("\t\t\t<div class=\"contaner\">\r\n");
      out.write("\t\t\t\t<img src=\"images/header.png\" class=\"con2\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/back.jpg\" class=\"con\">\r\n");
      out.write("\t\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"u_id\" id=\"u_id\" placeholder=\"아이디\" /><br>\r\n");
      out.write("\t\t\t\t\t<br> <input type=\"password\" name=\"u_pw\" id=\"u_pw\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"비밀번호\" /><br><br> <br> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"submit\" class=\"submits\" value=\" \"> <br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"join\">\r\n");
      out.write("\t\t\t\t\t<a href=\"join.jsp\">회원가입</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"find\">\r\n");
      out.write("\t\t\t\t\t<a href=\"idFind.jsp\">아이디찾기 |</a> <a href=\"pwFind.jsp\">|비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
